### DISCUSSION TITLE
My GitHub Action is not publishing my package to npm

### DISCUSSION THREAD

**Discussion by sebastianjnuwu** [JS-DevTools/npm-publish#170] [Q&A] [answered]
After "renovate" updated the dependency it stopped working I think it must be an error in the yml. Can anyone help me solve it?

```yml
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: 🕊️ publish 

on:
 workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm test
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: "https://registry.npmjs.org/"
```
