### DISCUSSION TITLE
How do we set this up to use the tag version as the publish version?

### DISCUSSION THREAD

**Discussion by jnovak-SM2Dev** [JS-DevTools/npm-publish#190] [Q&A] [answered]
Is there additional setup to have this publish with the tag version from github instead of using the number in the package.json file?

**Comment by mcous** [comment, marked as answer]
This action is designed to help you continuously publish to `npm` in the case where you are manually bumping the version number in `package.json`. I you push a tag to publish, you should probably [use `npm` directly](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages). You don't need this action if you're not CD'ing from `main`.

I have not tested this, but something like this could work to publish with the version from `git`:

```yaml
name: Publish Package
on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install development dependencies
        run: npm ci

      - name: Write git version to `package.json`
        run: npm version --from-git
      
      - name: Build package
        run: # whatever your package needs
      
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
