### ISSUE TITLE
Verify if repository its fork

### ISSUE THREAD

**Issue by Mikael-R** [JS-DevTools/npm-publish#10]
Dont run publish script if repository its fork

**Comment by JamesMessinger** [comment]
Logic like that belongs in your GitHub Actions script, not in this action.  See the following GitHub Actions documentation for details:

* [Adding an `if` statement to a job](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif)

* [Adding an `if` statement to a step](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif)

* [Context and expression syntax](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions)

For example, to skip your "publish" step on a fork, you could do something like this:

```yaml
- name: Publish to NPM
  if: github.repository == 'MyOrg/MyRepo'    # <--- Only run this step on your main repo
  uses: JS-DevTools/npm-publish@v1
  with:
    token: ${{ secrets.NPM_TOKEN }}
```
