### ISSUE TITLE
Support Github App

### ISSUE THREAD

**Issue by matanbaruch** [JS-DevTools/npm-publish#116]
Hey,
Is it possible to use this Github Action using Github App?
We would like to not use Personal Access Token of individual and use a Github App credentials to publish packages

**Comment by mcous** [comment]
Hi @matanbaruch! I assume that you are asking about publishing to the GitHub registry, since you're referring to GitHub tokens rather than npm tokens.

There is no need to create a Personal Access Token to use this action to publish to the GitHub Registry. Every GitHub Actions job is given a temporary access token automatically, accessible via `secrets.GITHUB_TOKEN`. To use it to publish a package, define your workflow to give that token publishing permission:

```yaml
name: Publish package to GitHub Packages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write  # < allow the built-in token to publish packages
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      
      # ... your project's specific build steps ...
      
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
