### ISSUE TITLE
Unable to publish package for the first time

### ISSUE THREAD

**Issue by abhishiv** [JS-DevTools/npm-publish#117]
Hello,

It seems that with v2, I can't publish the package for the first time. Or am I doing something wrong?

````
    - id: publish
      uses: JS-DevTools/npm-publish@v2
      with:
        registry: "https://registry.npmjs.org/"
        token: ${{ inputs.dir }}
        access: "public"
        package: ./${{ inputs.dir }}/package.json
    - if: steps.publish.outputs.type != 'none'
      run: |
        echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
      shell: bash
````

Error
```
Warning: Unexpected input(s) 'check-version', valid inputs are ['token', 'registry', 'package', 'tag', 'access', 'provenance', 'strategy', 'ignore-scripts', 'dry-run']
Run JS-DevTools/npm-publish@v2
  
Error: NpmCallError: Call to "npm publish" exited with non-zero exit code 1
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@gratico%2fbanyan - Not found
npm ERR! 404 
npm ERR! 404  '@gratico/banyan@0.2.4' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/[20](https://github.com/graticohq/mono/actions/runs/5495942601/jobs/10015646386#step:8:22)23-07-08T19_01_12_153Z-debug-0.log

```
