### ISSUE TITLE
I Don't Get `type` When Publishing To Private Repos

### ISSUE THREAD

**Issue by johnnyshankman** [JS-DevTools/npm-publish#128]
Setup:
```
      - name: Publish New ESLint Release on npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          strategy: upgrade

      - if: ${{ !steps.publish.outputs.type }}
        run: echo 'Version already exists' && exit 1
```

Does not work as expected. The `if` triggers every time even on successful upgrades.

This also does not work:
```
      - name: Publish New ESLint Release on npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          strategy: upgrade

      - if: ${{ steps.publish.outputs.type == '' }}
        run: echo 'Version already exists' && exit 1
```

Is there something I'm doing wrong?
