### ISSUE TITLE
`v`-prefix in `package.json` version causes false negative during version comparison

### ISSUE THREAD

**Issue by scraly** [JS-DevTools/npm-publish#139]
Hi,

I've got an issue.
Even if a npm package altready exists with the current version, the gh action wants to publish it again:

```
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@xxx%2fxxx - You cannot publish over the previously published versions: 0.34.0.
```

My GH action:

```
      - if: ${{ matrix.language == 'nodejs' && env.PUBLISH_NPM == 'true' }}
        uses: JS-DevTools/npm-publish@v2.2.1
        with:
          access: "public"
          token: ${{ env.NPM_TOKEN }}
          package: ${{github.workspace}}/sdk/nodejs/bin/package.json
          provenance: true
```

I've tried with `strategy: upgrade` without success.

Thanks
