### ISSUE TITLE
InvalidPackageVersionError: Package version must be a string, got "undefined"

### ISSUE THREAD

**Issue by michaelnlindsay** [JS-DevTools/npm-publish#160]
Hello!  Not sure how I arrived at this particular error.  I believe these are the salient parts of my workflow file:

```
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Test
        run: |
          npm test

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: ${{ env.NPM_REGISTRY_URL }}
          tag: "v${{ steps.version.outputs.value }}-${{ env.BETA_SUFFIX }}"
          dry-run: true
```
Can you spot what I may be missing?
