### ISSUE TITLE
Unable to publish package

### ISSUE THREAD

**Issue by LoeiFy** [JS-DevTools/npm-publish#182]
getting 404 error 

```
Error: NpmCallError: Call to "npm publish" exited with non-zero exit code 1
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@variousjs%2fregistry - Not found
npm ERR! 404 
npm ERR! 404  '@variousjs/registry@0.1.0' is not in this registry.
```

logs

https://github.com/variousjs/registry/actions/runs/8234758851/job/22517443228

configs

```yml
name: npm publish

on:
  push:
    branches:
      - master

jobs:
  pub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install
      - run: npm run build

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
```

<img width="556" alt="Screen Shot 2024-03-11 at 10 46 42 PM" src="https://github.com/JS-DevTools/npm-publish/assets/2193211/028782db-27a2-4b78-8fd7-091f0eca25a3">
<img width="1124" alt="Screen Shot 2024-03-11 at 10 46 59 PM" src="https://github.com/JS-DevTools/npm-publish/assets/2193211/42819415-f3e5-4011-9a53-1a660aa193e1">
