### ISSUE TITLE
[bug] steps.publish.type, steps.publish.version is always ""

### ISSUE THREAD

**Issue by narumincho** [JS-DevTools/npm-publish#2]
```yaml
name: npm publish

on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    name: npm publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@master
      - name: setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Install npm dependencies (npm ci)
        run: npm ci
      - name: npm publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: output version name
        run: echo type = ${{ steps.publish.type }}, version = ${{ steps.publish.version }}
```
output
```
type = , version =
```
