### ISSUE TITLE
Publishing on PR

### ISSUE THREAD

**Issue by shibdib** [JS-DevTools/npm-publish#20]
Having an issue where it's publishing when a version bump is in an unmerged PR

**Comment by JamesMessinger** [comment]
It's up to you to write your GitHub Actions workflow so that it only runs when you want it to.  For example, you could use [the `branches` keyword](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) to limit your workflow to only running on pushes to the `master` branch, like this:

```yaml
on:
  push:
    branches:
      - master
```

Or, if you want _most_ of your workflow to run, but only want to run the publish step on `master`, then you can use [the `if` keyword](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif), like this:

```yaml
steps:
  - name: Publish to NPM
    if: github.ref == 'refs/heads/master'
    uses: JS-DevTools/npm-publish@v1
    with:
      token: ${{ secrets.NPM_TOKEN }}
```
