### ISSUE TITLE
Tarball content is "empty"

### ISSUE THREAD

**Issue by tpmarc** [JS-DevTools/npm-publish#39]
When I try to publish through GH Actions, tarball content is:
```
npm notice === Tarball Contents === 
npm notice 1.5kB package.json
npm notice 894B  README.md   
npm notice === Tarball Details === 
```

But when I run locally (npm-publish), it is:
```
npm notice === Tarball Contents ===
npm notice 928B  README.md
npm notice 631B  dist/calendar/Calendar.d.ts
npm notice 463B  dist/calendar/CalendarContext.d.ts
npm notice 330B  dist/calendar/CalendarDate.d.ts
npm notice 298B  dist/calendar/CalendarDates.d.ts
npm notice 388B  dist/calendar/CalendarHeader.d.ts
npm notice 376B  dist/calendar/CalendarWeekday.d.ts
npm notice 150B  dist/calendar/useCalendarDates.d.ts
npm notice 77B   dist/calendar/useCalendarHeader.d.ts
npm notice 61B   dist/calendar/utils/generateDates.d.ts
npm notice 71B   dist/common/LocalesContext.d.ts
npm notice 49B   dist/index.d.ts
npm notice 4.0kB dist/react-date-controls.es.js
npm notice 4.6kB dist/react-date-controls.umd.js
npm notice 1.5kB package.json
npm notice === Tarball Details ===
```

My workflow file:
```yml
name: npm-publish
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.18.4
      - run: npm install
      - run: npm test
      - run: npm build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
```
