### ISSUE TITLE
[bug] Runs 3 times

### ISSUE THREAD

**Issue by Hunam6** [JS-DevTools/npm-publish#4]
My workflow file:

```  yml
on: release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{secrets.npm_token}}
```

![](https://i.imgur.com/k3ZgGRd.png)
