### ISSUE TITLE
Action not working in my workflow?

### ISSUE THREAD

**Issue by exoRift** [JS-DevTools/npm-publish#5]
I get this error in my workflow for some reason. I don't know why

![g](https://i.imgur.com/Q5Mj80O.png)

Step:

```yml
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
```
