### ISSUE TITLE
The registry parameter doesn't work

### ISSUE THREAD

**Issue by honzabilek4** [JS-DevTools/npm-publish#55]
When setting the `registry` parameter to a value. I expect that this value will be used during publication. Unfortunately, this doesn't happen, a default value is always used.
I've set it up to use "npm-private"
<img width="565" alt="Screenshot 2022-07-15 at 7 22 46" src="https://user-images.githubusercontent.com/7890555/179156626-83637d52-4af6-46d4-b9e5-6a02ad23303b.png">
But here you can see it uses different URL during publish.
<img width="721" alt="Screenshot 2022-07-15 at 7 23 11" src="https://user-images.githubusercontent.com/7890555/179156631-8fa369d5-aa0c-4a96-a46f-a8436aac1953.png">

**Comment by razor-x** [comment]
@honzabilek4 It should be handled by these line:

https://github.com/JS-DevTools/npm-publish/blob/e42e3720bfe21259120218c19fdbfedcf72692bd/src/npm-config.ts#L41
https://github.com/JS-DevTools/npm-publish/blob/e42e3720bfe21259120218c19fdbfedcf72692bd/src/npm.ts#L81

I can confirm it's working for me ok with this setup

```yaml
      - name: Publish
        uses: rxfork/npm-publish@v1
        with:
          access: public
          target: ${{ steps.meta.outputs.tgz }}
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com
```
