### ISSUE TITLE
Deprecation warning for 'set-output'

### ISSUE THREAD

**Issue by dht** [JS-DevTools/npm-publish#67]
When using the action as follows:
```yaml
- uses: JS-DevTools/npm-publish@v1
              with:
                  package: ./extra/apps/app-campaigns/package.json
                  token: ${{ secrets.NPM_TOKEN }}
                  access: public
```

We are getting a warning:
```txt
publish The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environ
```
