### ISSUE TITLE
Failed to publish

### ISSUE THREAD

**Issue by alexbeletsky** [JS-DevTools/npm-publish#78]
I've started to receive that error,

```
Run JS-DevTools/npm-publish@v1
  with:
    token: ***
    access: restricted
    registry: https://registry.npmjs.org/
    package: package.json
    dry-run: false
    check-version: true
Error: Error: Unable to read the NPM config file: /home/runner/.npmrc 
EISDIR: illegal operation on a directory, read
    at readNpmConfig (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/npm-config.ts:8[7](https://github.com/blogfoster/query-mapper/actions/runs/4688157894/jobs/8308328076#step:10:7):11)

Error: EISDIR: illegal operation on a directory, read
```

Actions file

```
name: Check, Test & Publish

on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          access: restricted

```

Any ideas?
