### ISSUE TITLE
custom publish command

### ISSUE THREAD

**Issue by nosovk** [JS-DevTools/npm-publish#9]
unfortunately for TS projects, especially Angular libs we often have to opt out from standard `npm publish` to custom script `npm run publish`.
See topic: https://stackoverflow.com/questions/38935176/how-to-npm-publish-specific-folder-but-as-package-root
often proposed workaround is using alternate publish script, like `npm run publish` that will do all the hacks.
Could you please add env variable `npmpublish` that will allow to override `npm publish` command with another non standard command.

**Comment by JamesMessinger** [comment]
That seems like a do-able feature.  Do you have time to submit a PR?

**Comment by thetrompf** [comment]
@nosovk I think there is an easier way, and kind of out of scope. It can be achieved with too much orchestration in all of the 3 ways this package supports.

Github workflows: (a single line added).
```yaml
---
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: ./path/to/custom/build-script.sh
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: YOUR_NPM_AUTH_TOKEN_HERE
        package: ./path/to/custom/package.json
```

Javascript package (a single line added).
```js
const npmPublish = require("@jsdevtools/npm-publish");

// Do custom build stuff
const { execSync } = require('child_process');
execSync('./path/to/custom/build-script.sh');

// Run npm-publish with options
await npmPublish({
  package: "./path/to/custom/package.json",
  token: "YOUR_NPM_AUTH_TOKEN_HERE"
});
```

CLI (a single line added).
```shell
$ ./path/to/custom/build-script.sh && \
  npm-publish --token=YOUR_NPM_AUTH_TOKEN_HERE ./path/to/custom/package.json
```
